apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: peterkoszorus/ambulance-ufe
  newName: peterkoszorus/ambulance-ufe
  newTag: 1.1.1  
- name: peterkoszorus/ambulance-wl-webapi
  newName: peterkoszorus/ambulance-wl-webapi
  newTag: 1.1.0
- name: peterkoszrous/ambulance-vaccination
  newName: peterkoszorus/ambulance-vaccination
  newTag: 1.1.0
- name: peterkoszorus/ambulance-webapi-vaccination
  newName: peterkoszorus/ambulance-webapi-vaccination
  newTag: 1.0.1

replacements:
  - targets:
      - select:
          group: fe.milung.eu
          version: v1
          kind: WebComponent
          name: pko-ambulance-ufe
        fieldPaths:
          - spec.hash-suffix
    source:
      version: v1
      kind: Deployment
      name: pko-ambulance-ufe-deployment
      fieldPath: spec.template.spec.containers.0.image
      options:
        delimiter: ':'
        index: 1
  - targets:
      - select:
          group: fe.milung.eu
          version: v1
          kind: WebComponent
          name: pko-ambulance-vaccination
        fieldPaths:
          - spec.hash-suffix
    source:
      version: v1
      kind: Deployment
      name: pko-ambulance-vaccination-deployment
      fieldPath: spec.template.spec.containers.0.image
      options:
        delimiter: ':'
        index: 0
