apiVersion: apps/v1
kind: Deployment
metadata:
  name: pko-ambulance-webapi-vaccination
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /pko-openapi-vaccination
            - name: BASE_URL
              value: /pko-openapi-ui-vaccination